services:
  postgres:
    image: postgres:16
    container_name: careertrack-postgres
    environment:
      POSTGRES_USER: career_user
      POSTGRES_PASSWORD: career_password
      POSTGRES_DB: careertrack_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7
    container_name: careertrack-redis
    ports:
      - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    container_name: careertrack-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@careertrack.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

  backend:
    image: samayohub/careertrack-backend:latest
    container_name: careertrack-backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis

  frontend:
    image: samayohub/careertrack-frontend:latest
    container_name: careertrack-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: